s

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -228,14 +228,20 @@ jobs:
           name: publish
           path: publish/
 
-      - name: Ensure `.runtimeconfig.json` Generation
+      - name: Debug Current Directory
         run: |
-          find . -name "*.csproj" -exec sh -c 'echo "<PropertyGroup>
-          <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
-          </PropertyGroup>" >> {}' \;
+          echo "Current directory: $(pwd)"
+          ls -la
 
-      - name: Publish Application
-        run: dotnet publish -c Release -o publish 9soat-g63-mc-king.sln
+      - name: Locate Solution and Publish
+        run: |
+          SOLUTION=$(find . -name "9soat-g63-mc-king.sln" | head -n 1)
+          if [ -z "$SOLUTION" ]; then
+            echo "Error: Solution file not found!"
+            exit 1
+          fi
+          echo "Found solution: $SOLUTION"
+          dotnet publish "$SOLUTION" -c Release -o publish
 
       - name: Verify .runtimeconfig.json Presence
         run: |
@@ -260,3 +266,4 @@ jobs:
           deployment_package: ./application.zip
           wait_for_environment_recovery: 90
           use_existing_version_if_available: false
+
